package company.domain.components;

public enum Manufacturers {
    AMD, INTEL, AMPERE, APPLE,
    ASUS, MSI, GIGABYTE, ASROCK, BIOSTAR,
    DELL, HP, IBM, SUPERMICRO,
    KINGSTON, G_SKILL, ADATA, GOODRAM, APACER, SAMSUNG,
    NVIDIA, PNY,
    SEAGATE, WESTERN_DIGITAL, HITACHI,
    CHIEFTEC, CORSAIR, BE_QUIET, ENERMAX, SEASONIC, ZALMAN,
}
